### PR TITLE
Fix#167

### PR DESCRIPTION
**Pull request by roguxivlo**

### CODE REVIEW

**Comment by roguxivlo** [comment]
I'll fix this error tmrw

**Comment by DragonGamesStudios** [comment]
Yeah, there was a change that broke a few things a while ago. It's fixed now, but you probably need to rebase.

**Comment by DragonGamesStudios** [comment]
Nevermind, `mid` is just straight up broken

**Comment by DragonGamesStudios** [comment]
Alright, a fix is up. The python file still crashes, though, so there's certainly an error there

**Comment by roguxivlo** [comment]
after some delay, I got it to work:)

**Pull request merged**
